Makefile automation command + freeband fixes

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -1442,3 +1442,20 @@ lint:
 doc:
 	@echo "Running doxygen . . ."
 	@etc/make-doc.sh
+
+doc-test:
+	@echo "Running code example extraction script . . ."
+	python3 ./etc/extract-doc-examples.py ./include/libsemigroups/ -r
+	@echo "Formatting test-docs-code-examples.cpp . . ."
+	clang-format -i tests/test-docs-code-examples.cpp
+	@echo "Compiling . . ."
+	@if make test_docs_code_examples -s -j8 2>&1; then \
+		echo ""; \
+		echo "Running test_docs_code_examples . . ."; \
+		./test_docs_code_examples; \
+	else \
+		echo ""; \
+		echo "Compilation failed"; \
+		exit 1; \
+	fi
+	@echo ""
